class CountryRegions {
  const CountryRegions._();

  static final Map<String, String> _regionMap = {
    for (final country in _europe) country: 'Europe',
    for (final country in _northAmerica) country: 'North America',
    for (final country in _southAmerica) country: 'South America',
    for (final country in _asia) country: 'Asia',
    for (final country in _africa) country: 'Africa',
    for (final country in _oceania) country: 'Oceania',
  };

  static String? regionFor(String? country) {
    if (country == null || country.trim().isEmpty) {
      return null;
    }
    return _regionMap[_normalize(country)];
  }

  static String _normalize(String value) => value.trim().toLowerCase();

  static const List<String> _europe = [
    'albania',
    'andorra',
    'austria',
    'belgium',
    'bosnia and herzegovina',
    'bulgaria',
    'croatia',
    'cyprus',
    'czech republic',
    'czechia',
    'denmark',
    'estonia',
    'finland',
    'france',
    'germany',
    'greece',
    'hungary',
    'iceland',
    'ireland',
    'italy',
    'latvia',
    'liechtenstein',
    'lithuania',
    'luxembourg',
    'malta',
    'moldova',
    'monaco',
    'montenegro',
    'netherlands',
    'north macedonia',
    'norway',
    'poland',
    'portugal',
    'romania',
    'san marino',
    'serbia',
    'slovakia',
    'slovenia',
    'spain',
    'sweden',
    'switzerland',
    'ukraine',
    'united kingdom',
    'england',
    'scotland',
    'wales',
    'vatican city',
  ];

  static const List<String> _northAmerica = [
    'canada',
    'united states',
    'usa',
    'mexico',
    'guatemala',
    'belize',
    'honduras',
    'el salvador',
    'nicaragua',
    'costa rica',
    'panama',
    'bahamas',
    'cuba',
    'jamaica',
    'haiti',
    'dominican republic',
    'trinidad and tobago',
    'barbados',
  ];

  static const List<String> _southAmerica = [
    'argentina',
    'bolivia',
    'brazil',
    'chile',
    'colombia',
    'ecuador',
    'guyana',
    'paraguay',
    'peru',
    'suriname',
    'uruguay',
    'venezuela',
  ];

  static const List<String> _asia = [
    'afghanistan',
    'armenia',
    'azerbaijan',
    'bahrain',
    'bangladesh',
    'bhutan',
    'brunei',
    'cambodia',
    'china',
    'georgia',
    'india',
    'indonesia',
    'iran',
    'iraq',
    'israel',
    'japan',
    'jordan',
    'kazakhstan',
    'kuwait',
    'kyrgyzstan',
    'laos',
    'lebanon',
    'malaysia',
    'maldives',
    'mongolia',
    'myanmar',
    'nepal',
    'north korea',
    'oman',
    'pakistan',
    'palestine',
    'philippines',
    'qatar',
    'saudi arabia',
    'singapore',
    'south korea',
    'sri lanka',
    'syria',
    'taiwan',
    'tajikistan',
    'thailand',
    'timor-leste',
    'turkey',
    'turkiye',
    'turkmenistan',
    'united arab emirates',
    'uae',
    'uzbekistan',
    'vietnam',
    'yemen',
  ];

  static const List<String> _africa = [
    'algeria',
    'angola',
    'benin',
    'botswana',
    'burkina faso',
    'burundi',
    'cameroon',
    'cape verde',
    'chad',
    'comoros',
    'congo',
    'democratic republic of the congo',
    'djibouti',
    'egypt',
    'equatorial guinea',
    'eritrea',
    'eswatini',
    'ethiopia',
    'gabon',
    'gambia',
    'ghana',
    'guinea',
    'guinea-bissau',
    'ivory coast',
    'kenya',
    'lesotho',
    'liberia',
    'libya',
    'madagascar',
    'malawi',
    'mali',
    'mauritania',
    'mauritius',
    'morocco',
    'mozambique',
    'namibia',
    'niger',
    'nigeria',
    'rwanda',
    'senegal',
    'seychelles',
    'sierra leone',
    'somalia',
    'south africa',
    'south sudan',
    'sudan',
    'tanzania',
    'togo',
    'tunisia',
    'uganda',
    'zambia',
    'zimbabwe',
  ];

  static const List<String> _oceania = [
    'australia',
    'new zealand',
    'fiji',
    'papua new guinea',
    'samoa',
    'tonga',
    'vanuatu',
  ];
}
